[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\data_sharing_framework'

[projects.core]
path = 'Data Sharing Framework Core\Data Sharing Framework Core Build.lvproj'

[[build.steps]]
name = 'Data Sharing Framework Core - Windows'
type = 'lvBuildSpec'
project = '{core}'
target = 'My Computer'
build_spec = 'Data Sharing Framework Core'

[[package]]
type = 'nipkg'
payload_dir = 'Source\Built\DSF Core'
install_destination = 'documents\National Instruments\Data Sharing Framework\Core'
control_file = 'control_dsf_core'
package_output_dir = 'Source\Built'